#!/usr/bin/env bash
# This script displays a story base on /etc/passwd

#!/bin/bash

while IFS=':' read -r username _ uid gid _ home shell
do
    read -r _ _ _ info _ < <(grep "^$username:" /etc/passwd)
    read -r _ _ password _ < <(grep "^$username:" /etc/shadow)

    echo "The user $username is part of the $gid gang, lives in $home and rides $shell."
    echo "User ID's place is protected by the passcode $password, more info about the user here: $info"
    echo
done < "/etc/passwd"

