#!/usr/bin/env bash
# This script the time for 12 hours(display hours from 0 to 12) and 59 minutes(display minutes from 1 to 59)
hour=0; while [ $hour -lt 24 ]; do echo "Hour: $((hour%12))"; for minute in {1..59}; do echo "$minute"; done; hour=$((hour+1)); done
