#!/usr/bin/env bash
# This script the time for 12 hours(display hours from 0 to 12) and 59 minutes(display minutes from 1 to 59)
hour=0
while [ $hour -lt 12 ]; do minute=1; while [ $minute -le 59 ]; do echo "$hour:$minute"; minute=$((minute+1)); done; hour=$((hour+1)); done
