#!/usr/bin/env bash
#script that displays:
# The content of the current directory
# In a list format
# Where only the part of the name after the first dash is displayed 

for file in *; do if [[ -f $file && ! $file == .* && $file =~ -(.*) ]]; then echo "${BASH_REMATCH[1]}"; fi; done

