#!/usr/bin/env bash
# this script does the following;
# Creates the file /var/run/myscript.pid containing its PID
echo $$ > /var/run/myscript.pid
# Displays To infinity and beyond indefinitely
while true; do echo "To infinity and beyond"; done

#Displays I hate the kill command when receiving a SIGTERM signal
#Displays Y U no love me?! when receiving a SIGINT signal
#Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal

function cleanup() {
        rm /var/run/myscript.pid
        exit 1
}

trap "echoI hate the kill comman; cleanup" SIGTERM
trap "echo Y U no love me?!" SIGINT
trap "cleanup" SIGQUIT
